backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"   # folder where uploaded images go
public_folder: "/assets/images" # URL used in HTML

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
